use statistic;

create table WEBSTAT (
	SEQ 			INTEGER PRIMARY KEY AUTO_INCREMENT,
	VISIT_DATE 		INTEGER,
    VISIT_DEVICE 	INTEGER,
    CONTENT 		VARCHAR(255) 
);



create table PRAISE(
	PRAISE_NO		INTEGER PRIMARY KEY AUTO_INCREMENT,
    TITLE			VARCHAR(50) NOT NULL,
    FIRST_LYLICS	VARCHAR(50),
    LYLICS			TEXT,
    CODE			CHAR(4)
);


CREATE TABLE WORSHIP(
	WORSHIP_NO			INTEGER PRIMARY KEY AUTO_INCREMENT,
    WORSHIP_DATE		DATE,
    WORSHIP_LEADER		VARCHAR(20),
    WORSHIP_WEEK		INTEGER,
    WORSHIP_
);

CREATE TABLE WORSHIP_CONTI(
	CONTI_NO	INTEGER,
    PRAISE_NO	INTEGER,
    FOREIGN KEY (PRAISE_NO) REFERENCES PRAISE (PRAISE_NO)
);




